In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("train_IPL.csv")
data.head()

C:\Users\sidak\AppData\Local\Temp\ipykernel_12284\1283069277.py:1: DtypeWarning: Columns (35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("train_IPL.csv")

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball,toss_winner,toss_decision,city,result_type,season,match_won_by
0,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,1,SC Ganguly,BB McCullum,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
1,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,2,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
2,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,NaN,NaN,1,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
3,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
4,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,4,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders

In [3]:
data.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Ball Rebowled', 'Extra Type', 'Wicket',
       'Dismissal Method', 'Player Out', 'Innings Runs', 'Innings Wickets',
       'Target Score', 'Runs to Get', 'Balls Remaining', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'Valid Ball', 'toss_winner', 'toss_decision',
       'city', 'result_type', 'season', 'match_won_by'],
      dtype='object')

In [4]:
data.head(10)

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball,toss_winner,toss_decision,city,result_type,season,match_won_by
0,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,1,SC Ganguly,BB McCullum,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
1,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,2,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
2,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,NaN,NaN,1,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
3,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
4,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,4,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
5,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,5,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
6,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,6,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
7,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,1,BB McCullum,SC Ganguly,...,NaN,NaN,0,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
8,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,2,BB McCullum,SC Ganguly,...,NaN,NaN,4,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
9,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,3,BB McCullum,SC Ganguly,...,NaN,NaN,4,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders

In [5]:
data['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 35705
Chennai Super Kings            33885
Kolkata Knight Riders          31477
Rajasthan Royals               27230
Royal Challengers Bangalore    26801
Sunrisers Hyderabad            21439
Kings XI Punjab                20162
Delhi Daredevils               15709
Delhi Capitals                 12047
Gujarat Titans                  8265
Lucknow Super Giants            7176
Punjab Kings                    7168
Deccan Chargers                 7013
Unknown                         4516
Royal Challengers Bengaluru     3355
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

In [6]:
data['match_won_by'] = data['match_won_by'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Kings XI Punjab': 'Punjab Kings'
})

In [7]:
data['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 35705
Chennai Super Kings            33885
Kolkata Knight Riders          31477
Royal Challengers Bengaluru    30156
Delhi Capitals                 27756
Punjab Kings                   27330
Rajasthan Royals               27230
Sunrisers Hyderabad            21439
Gujarat Titans                  8265
Lucknow Super Giants            7176
Deccan Chargers                 7013
Unknown                         4516
Rising Pune Supergiants         3488
Gujarat Lions                   3063
Pune Warriors                   2883
Kochi Tuskers Kerala            1322
Name: count, dtype: int64

In [8]:
data["Bat First"].value_counts()

Bat First
Mumbai Indians                 33399
Chennai Super Kings            32225
Kolkata Knight Riders          29130
Royal Challengers Bangalore    28621
Rajasthan Royals               25586
Sunrisers Hyderabad            23855
Kings XI Punjab                22916
Delhi Daredevils               16559
Delhi Capitals                 11083
Deccan Chargers                10335
Punjab Kings                    8773
Lucknow Super Giants            7202
Gujarat Titans                  6196
Pune Warriors                   4759
Royal Challengers Bengaluru     3554
Gujarat Lions                   3309
Rising Pune Supergiant          1960
Kochi Tuskers Kerala            1650
Rising Pune Supergiants         1592
Name: count, dtype: int64

In [9]:
data["Bat Second"].value_counts()

Bat Second
Kolkata Knight Riders          32191
Mumbai Indians                 32138
Rajasthan Royals               29666
Royal Challengers Bangalore    27942
Chennai Super Kings            27295
Kings XI Punjab                22213
Sunrisers Hyderabad            21822
Delhi Daredevils               20952
Delhi Capitals                 13510
Deccan Chargers                 7738
Punjab Kings                    6976
Gujarat Titans                  6801
Pune Warriors                   6078
Lucknow Super Giants            5875
Gujarat Lions                   3802
Royal Challengers Bengaluru     2379
Rising Pune Supergiant          1868
Rising Pune Supergiants         1603
Kochi Tuskers Kerala            1546
Name: count, dtype: int64

In [10]:
drop_teams = ["Rising Pune Supergiant", "Rising Pune Supergiants","Kochi Tuskers Kerala"]
target_columns = ["Bat First", "Bat Second", "match_won_by"]
data = data[~data[target_columns].isin(drop_teams).any(axis=1)]

In [11]:
data["match_won_by"].value_counts()

match_won_by
Mumbai Indians                 35217
Chennai Super Kings            33636
Kolkata Knight Riders          30852
Royal Challengers Bengaluru    29202
Delhi Capitals                 27042
Rajasthan Royals               27021
Punjab Kings                   26599
Sunrisers Hyderabad            21195
Gujarat Titans                  8265
Lucknow Super Giants            7176
Deccan Chargers                 6785
Unknown                         4516
Pune Warriors                   2637
Gujarat Lions                   2342
Name: count, dtype: int64

In [12]:
data.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Ball Rebowled', 'Extra Type', 'Wicket',
       'Dismissal Method', 'Player Out', 'Innings Runs', 'Innings Wickets',
       'Target Score', 'Runs to Get', 'Balls Remaining', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'Valid Ball', 'toss_winner', 'toss_decision',
       'city', 'result_type', 'season', 'match_won_by'],
      dtype='object')

In [13]:
columns_to_drop = ['Ball Rebowled', 'Innings Wickets','Valid Ball']
data.drop(columns_to_drop,  axis = 1, inplace=True)

In [14]:
data.shape

(262485, 35)

In [15]:
data['Venue'].value_counts().sum()

262485

In [16]:
data['Venue'].value_counts()

Venue
Wankhede Stadium                                                      28700
Eden Gardens                                                          22315
M Chinnaswamy Stadium                                                 21999
MA Chidambaram Stadium                                                21883
Rajiv Gandhi International Stadium                                    18851
Sawai Mansingh Stadium                                                14243
Punjab Cricket Association Stadium                                    14239
Feroz Shah Kotla                                                      13227
Dubai International Cricket Stadium                                   11229
Maharashtra Cricket Association Stadium                                9632
Dr DY Patil Sports Academy                                             8652
Arun Jaitley Stadium                                                   8319
Sheikh Zayed Stadium                                                   6925
Narendra Modi Stadium                                                  6681
Sharjah Cricket Stadium                                                6672
Brabourne Stadium                                                      6526
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           4494
Kingsmead                                                              3643
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    3313
Himachal Pradesh Cricket Association Stadium                           3141
Sardar Patel Stadium                                                   2893
SuperSport Park                                                        2866
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     2166
New Wanderers Stadium                                                  1940
Saurashtra Cricket Association Stadium                                 1912
Zayed Cricket Stadium                                                  1874
Barabati Stadium                                                       1695
St George's Park                                                       1677
JSCA International Stadium Complex                                     1671
Newlands                                                               1539
Shaheed Veer Narayan Singh International Stadium                       1431
Holkar Cricket Stadium                                                 1310
Barsapara Cricket Stadium                                              1223
Green Park                                                              921
Vidarbha Cricket Association Stadium                                    742
De Beers Diamond Oval                                                   726
Buffalo Park                                                            715
OUTsurance Oval                                                         500
Name: count, dtype: int64

In [17]:
data['Venue'].unique

<bound method Series.unique of 0          M Chinnaswamy Stadium
1          M Chinnaswamy Stadium
2          M Chinnaswamy Stadium
3          M Chinnaswamy Stadium
4          M Chinnaswamy Stadium
                   ...
272699    Sawai Mansingh Stadium
272700    Sawai Mansingh Stadium
272701    Sawai Mansingh Stadium
272702    Sawai Mansingh Stadium
272703    Sawai Mansingh Stadium
Name: Venue, Length: 262485, dtype: object>

In [18]:
data.head()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,toss_winner,toss_decision,city,result_type,season,match_won_by
0,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,1,SC Ganguly,BB McCullum,...,0,NaN,NaN,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
1,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,2,BB McCullum,SC Ganguly,...,1,NaN,NaN,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
2,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,1,NaN,NaN,1,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
3,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,1,NaN,NaN,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders
4,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,4,BB McCullum,SC Ganguly,...,1,NaN,NaN,0,Royal Challengers Bangalore,field,Bengaluru,NaN,2007/08,Kolkata Knight Riders

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 262485 entries, 0 to 272703
Data columns (total 35 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 262485 non-null  int64
 1   Date                     262485 non-null  object
 2   Venue                    262485 non-null  object
 3   Bat First                262485 non-null  object
 4   Bat Second               262176 non-null  object
 5   Innings                  262485 non-null  int64
 6   Over                     262485 non-null  int64
 7   Ball                     262485 non-null  int64
 8   Batter                   262485 non-null  object
 9   Non Striker              262485 non-null  object
 10  Bowler                   262485 non-null  object
 11  Batter Runs              262485 non-null  int64
 12  Extra Runs               262485 non-null  int64
 13  Runs From Ball           262485 non-null  int64
 14  Extra Type               262485 non-null  object
 15  Wicket                   262485 non-null  int64
 16  Dismissal Method         13045 non-null   object
 17  Player Out               13045 non-null   object
 18  Innings Runs             262485 non-null  int64
 19  Target Score             262485 non-null  int64
 20  Runs to Get              126489 non-null  float64
 21  Balls Remaining          262485 non-null  int64
 22  Total Batter Runs        262485 non-null  int64
 23  Total Non Striker Runs   262485 non-null  int64
 24  Batter Balls Faced       262485 non-null  int64
 25  Non Striker Balls Faced  262485 non-null  int64
 26  Player Out Runs          13045 non-null   float64
 27  Player Out Balls Faced   13045 non-null   float64
 28  Bowler Runs Conceded     262485 non-null  int64
 29  toss_winner              262485 non-null  object
 30  toss_decision            262485 non-null  object
 31  city                     262485 non-null  object
 32  result_type              4516 non-null    object
 33  season                   262485 non-null  object
 34  match_won_by             262485 non-null  object
dtypes: float64(3), int64(16), object(16)
memory usage: 72.1+ MB

In [20]:
data.describe()

,Match ID,Innings,Over,Ball,Batter Runs,Extra Runs,Runs From Ball,Wicket,Innings Runs,Target Score,Runs to Get,Balls Remaining,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded
count,2.624850e+05,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,126489.000000,262485.000000,262485.000000,262485.000000,262485.000000,262485.000000,13045.000000,13045.000000,262485.000000
mean,9.339761e+05,1.483590,10.199535,3.488234,1.274709,0.068023,1.342732,0.049698,76.949113,168.738663,94.522646,61.351292,17.372216,16.727043,13.433004,13.236916,18.956842,15.227750,1.318243
std,3.817944e+05,0.502764,5.682485,1.708649,1.648759,0.343530,1.635464,0.217321,49.820459,32.465970,51.341009,34.123571,18.453335,17.972599,12.003812,11.937979,19.842323,12.736877,1.640066
min,3.359820e+05,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,43.000000,-10.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483500e+05,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,36.000000,149.000000,54.000000,32.000000,3.000000,3.000000,4.000000,4.000000,4.000000,5.000000,0.000000
50%,1.082597e+06,1.000000,10.000000,3.000000,1.000000,0.000000,1.000000,0.000000,73.000000,169.000000,93.000000,62.000000,11.000000,11.000000,10.000000,10.000000,12.000000,11.000000,1.000000
75%,1.254114e+06,2.000000,15.000000,5.000000,1.000000,0.000000,1.000000,0.000000,113.000000,189.000000,133.000000,91.000000,26.000000,25.000000,20.000000,20.000000,28.000000,22.000000,1.000000
max,1.473487e+06,6.000000,20.000000,7.000000,6.000000,7.000000,7.000000,1.000000,287.000000,288.000000,287.000000,120.000000,175.000000,175.000000,74.000000,73.000000,141.000000,71.000000,7.000000

In [21]:
data.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Extra Type', 'Wicket',
       'Dismissal Method', 'Player Out', 'Innings Runs', 'Target Score',
       'Runs to Get', 'Balls Remaining', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'toss_winner', 'toss_decision', 'city',
       'result_type', 'season', 'match_won_by'],
      dtype='object')

In [22]:
data.shape

(262485, 35)

In [23]:
data.isnull().sum()

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                    309
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Extra Type                      0
Wicket                          0
Dismissal Method           249440
Player Out                 249440
Innings Runs                    0
Target Score                    0
Runs to Get                135996
Balls Remaining                 0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            249440
Player Out Balls Faced     249440
Bowler Runs Conceded            0
toss_winner                     0
toss_decision                   0
city                            0
result_type                257969
season                          0
match_won_by                    0
dtype: int64

In [24]:
data.dropna()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,toss_winner,toss_decision,city,result_type,season,match_won_by
15311,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,4,6,BB McCullum,CH Gayle,...,15,3.0,9.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15341,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,9,2,CH Gayle,LR Shukla,...,8,41.0,33.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15350,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,10,5,LR Shukla,BJ Hodge,...,4,13.0,13.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15356,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,11,5,BJ Hodge,SC Ganguly,...,3,5.0,7.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15377,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,14,6,SB Bangar,SC Ganguly,...,13,2.0,9.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268469,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,6,3,SV Samson,YBK Jaiswal,...,15,31.0,18.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268485,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,9,1,R Parag,YBK Jaiswal,...,20,8.0,11.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268516,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,14,2,YBK Jaiswal,N Rana,...,14,51.0,37.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268542,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,18,4,N Rana,Dhruv Jurel,...,12,51.0,28.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268557,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,20,6,Dhruv Jurel,SO Hetmyer,...,9,26.0,17.0,1,Rajasthan Royals,field,Delhi,tie,2025,Unknown

In [25]:
data.dropna()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,toss_winner,toss_decision,city,result_type,season,match_won_by
15311,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,4,6,BB McCullum,CH Gayle,...,15,3.0,9.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15341,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,9,2,CH Gayle,LR Shukla,...,8,41.0,33.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15350,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,10,5,LR Shukla,BJ Hodge,...,4,13.0,13.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15356,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,11,5,BJ Hodge,SC Ganguly,...,3,5.0,7.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
15377,392190,2009-04-23,Newlands,Rajasthan Royals,Kolkata Knight Riders,2,14,6,SB Bangar,SC Ganguly,...,13,2.0,9.0,0,Kolkata Knight Riders,field,Cape Town,tie,2009,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268469,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,6,3,SV Samson,YBK Jaiswal,...,15,31.0,18.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268485,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,9,1,R Parag,YBK Jaiswal,...,20,8.0,11.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268516,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,14,2,YBK Jaiswal,N Rana,...,14,51.0,37.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268542,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,18,4,N Rana,Dhruv Jurel,...,12,51.0,28.0,0,Rajasthan Royals,field,Delhi,tie,2025,Unknown
268557,1473469,2025-04-16,Arun Jaitley Stadium,Delhi Capitals,Rajasthan Royals,2,20,6,Dhruv Jurel,SO Hetmyer,...,9,26.0,17.0,1,Rajasthan Royals,field,Delhi,tie,2025,Unknown

In [26]:
data.fillna(0)

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,toss_winner,toss_decision,city,result_type,season,match_won_by
0,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,1,SC Ganguly,BB McCullum,...,0,0.0,0.0,0,Royal Challengers Bangalore,field,Bengaluru,0,2007/08,Kolkata Knight Riders
1,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,2,BB McCullum,SC Ganguly,...,1,0.0,0.0,0,Royal Challengers Bangalore,field,Bengaluru,0,2007/08,Kolkata Knight Riders
2,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,1,0.0,0.0,1,Royal Challengers Bangalore,field,Bengaluru,0,2007/08,Kolkata Knight Riders
3,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,3,BB McCullum,SC Ganguly,...,1,0.0,0.0,0,Royal Challengers Bangalore,field,Bengaluru,0,2007/08,Kolkata Knight Riders
4,335982,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,4,BB McCullum,SC Ganguly,...,1,0.0,0.0,0,Royal Challengers Bangalore,field,Bengaluru,0,2007/08,Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272699,1473487,2025-05-01,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,2,16,3,Akash Madhwal,JC Archer,...,24,0.0,0.0,1,Rajasthan Royals,field,Jaipur,0,2025,Mumbai Indians
272700,1473487,2025-05-01,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,2,16,4,JC Archer,Akash Madhwal,...,8,0.0,0.0,1,Rajasthan Royals,field,Jaipur,0,2025,Mumbai Indians
272701,1473487,2025-05-01,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,2,16,5,Akash Madhwal,JC Archer,...,25,0.0,0.0,1,Rajasthan Royals,field,Jaipur,0,2025,Mumbai Indians
272702,1473487,2025-05-01,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,2,16,6,JC Archer,Akash Madhwal,...,9,0.0,0.0,1,Rajasthan Royals,field,Jaipur,0,2025,Mumbai Indians
272703,1473487,2025-05-01,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,2,17,1,JC Archer,Akash Madhwal,...,9,30.0,27.0,0,Rajasthan Royals,field,Jaipur,0,2025,Mumbai Indians

In [27]:
data['Venue'].value_counts()

Venue
Wankhede Stadium                                                      28700
Eden Gardens                                                          22315
M Chinnaswamy Stadium                                                 21999
MA Chidambaram Stadium                                                21883
Rajiv Gandhi International Stadium                                    18851
Sawai Mansingh Stadium                                                14243
Punjab Cricket Association Stadium                                    14239
Feroz Shah Kotla                                                      13227
Dubai International Cricket Stadium                                   11229
Maharashtra Cricket Association Stadium                                9632
Dr DY Patil Sports Academy                                             8652
Arun Jaitley Stadium                                                   8319
Sheikh Zayed Stadium                                                   6925
Narendra Modi Stadium                                                  6681
Sharjah Cricket Stadium                                                6672
Brabourne Stadium                                                      6526
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium           4494
Kingsmead                                                              3643
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                    3313
Himachal Pradesh Cricket Association Stadium                           3141
Sardar Patel Stadium                                                   2893
SuperSport Park                                                        2866
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur     2166
New Wanderers Stadium                                                  1940
Saurashtra Cricket Association Stadium                                 1912
Zayed Cricket Stadium                                                  1874
Barabati Stadium                                                       1695
St George's Park                                                       1677
JSCA International Stadium Complex                                     1671
Newlands                                                               1539
Shaheed Veer Narayan Singh International Stadium                       1431
Holkar Cricket Stadium                                                 1310
Barsapara Cricket Stadium                                              1223
Green Park                                                              921
Vidarbha Cricket Association Stadium                                    742
De Beers Diamond Oval                                                   726
Buffalo Park                                                            715
OUTsurance Oval                                                         500
Name: count, dtype: int64

In [28]:



data["Batter"] = data["Batter"].str.strip().str.title()
data["Non Striker"] = data["Non Striker"].str.strip().str.title()
data["Bowler"] = data["Bowler"].str.strip().str.title()
data["Player Out"] = data["Player Out"].str.strip().str.title()

In [29]:
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(numerical_cols)

['Match ID', 'Innings', 'Over', 'Ball', 'Batter Runs', 'Extra Runs', 'Runs From Ball', 'Wicket', 'Innings Runs', 'Target Score', 'Runs to Get', 'Balls Remaining', 'Total Batter Runs', 'Total Non Striker Runs', 'Batter Balls Faced', 'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced', 'Bowler Runs Conceded']

In [30]:
numerical_df =pd.DataFrame(data[numerical_cols])
numerical_df.corr()

,Match ID,Innings,Over,Ball,Batter Runs,Extra Runs,Runs From Ball,Wicket,Innings Runs,Target Score,Runs to Get,Balls Remaining,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded
Match ID,1.000000,-0.000954,0.007555,0.000896,0.040344,-0.004491,0.039728,0.001381,0.096113,0.265722,0.075098,-0.007522,0.055326,0.061382,-0.006061,0.002181,0.053666,-0.005041,0.041648
Innings,-0.000954,1.000000,-0.049965,-0.005228,-0.005907,0.000430,-0.005864,0.000857,-0.041012,0.024893,NaN,0.050183,-0.015598,-0.017919,-0.020763,-0.022526,-0.056225,-0.061450,-0.005952
Over,0.007555,-0.049965,1.000000,-0.006730,0.077875,0.005588,0.079682,0.072245,0.931376,0.049686,-0.823600,-0.998728,0.300741,0.308162,0.306079,0.328374,0.241926,0.231128,0.079402
Ball,0.000896,-0.005228,-0.006730,1.000000,0.000749,-0.005325,-0.000363,0.004237,0.041352,0.002038,-0.030500,-0.043389,0.013433,0.017177,0.005594,0.025927,-0.010204,-0.025966,-0.000284
Batter Runs,0.040344,-0.005907,0.077875,0.000749,1.000000,-0.142725,0.978150,-0.172339,0.130423,0.100484,-0.064621,-0.078575,0.243400,0.051736,0.154144,0.041963,-0.010437,-0.020727,0.986950
Extra Runs,-0.004491,0.000430,0.005588,-0.005325,-0.142725,1.000000,0.066165,-0.042068,0.011908,0.012033,0.000871,-0.001810,-0.002218,-0.005843,0.000204,-0.008690,-0.000740,-0.008625,-0.019841
Runs From Ball,0.039728,-0.005864,0.079682,-0.000363,0.978150,0.066165,1.000000,-0.182576,0.133984,0.103829,-0.064921,-0.079594,0.244912,0.050930,0.155440,0.040478,-0.010084,-0.022329,0.990805
Wicket,0.001381,0.000857,0.072245,0.004237,-0.172339,-0.042068,-0.182576,1.000000,0.064963,-0.010070,-0.032878,-0.072614,-0.206375,0.006694,-0.245085,0.002195,NaN,NaN,-0.178713
Innings Runs,0.096113,-0.041012,0.931376,0.041352,0.130423,0.011908,0.133984,0.064963,1.000000,0.247632,-0.798105,-0.932523,0.383944,0.385505,0.320664,0.339848,0.332812,0.251375,0.133503
Target Score,0.265722,0.024893,0.049686,0.002038,0.100484,0.012033,0.103829,-0.010070,0.247632,1.000000,0.409728,-0.049621,0.171653,0.161259,0.057046,0.051715,0.185144,0.067395,0.103734
Runs to Get,0.075098,NaN,-0.823600,-0.030500,-0.064621,0.000871,-0.064921,-0.032878,-0.798105,0.409728,1.000000,0.824678,-0.322038,-0.329922,-0.341678,-0.360294,-0.270897,-0.269152,-0.065168
Balls Remaining,-0.007522,0.050183,-0.998728,-0.043389,-0.078575,-0.001810,-0.079594,-0.072614,-0.932523,-0.049621,0.824678,1.000000,-0.301114,-0.308778,-0.306093,-0.329439,-0.241213,-0.229695,-0.079304
Total Batter Runs,0.055326,-0.015598,0.300741,0.013433,0.243400,-0.002218,0.244912,-0.206375,0.383944,0.171653,-0.322038,-0.301114,1.000000,0.124010,0.925230,0.114971,-0.013064,-0.025879,0.245551
Total Non Striker Runs,0.061382,-0.017919,0.308162,0.017177,0.051736,-0.005843,0.050930,0.006694,0.385505,0.161259,-0.329922,-0.308778,0.124010,1.000000,0.109827,0.928561,0.117783,0.097865,0.051382
Batter Balls Faced,-0.006061,-0.020763,0.306079,0.005594,0.154144,0.000204,0.155440,-0.245085,0.320664,0.057046,-0.341678,-0.306093,0.925230,0.109827,1.000000,0.114477,-0.014663,-0.026392,0.155169
Non Striker Balls Faced,0.002181,-0.022526,0.328374,0.025927,0.041963,-0.008690,0.040478,0.002195,0.339848,0.051715,-0.360294,-0.329439,0.114971,0.928561,0.114477,1.000000,0.105687,0.103921,0.040950
Player Out Runs,0.053666,-0.056225,0.241926,-0.010204,-0.010437,-0.000740,-0.010084,NaN,0.332812,0.185144,-0.270897,-0.241213,-0.013064,0.117783,-0.014663,0.105687,1.000000,0.925222,-0.009090
Player Out Balls Faced,-0.005041,-0.061450,0.231128,-0.025966,-0.020727,-0.008625,-0.022329,NaN,0.251375,0.067395,-0.269152,-0.229695,-0.025879,0.097865,-0.026392,0.103921,0.925222,1.000000,-0.020737
Bowler Runs Conceded,0.041648,-0.005952,0.079402,-0.000284,0.986950,-0.019841,0.990805,-0.178713,0.133503,0.103734,-0.065168,-0.079304,0.245551,0.051382,0.155169,0.040950,-0.009090,-0.020737,1.000000

In [31]:
y = data['match_won_by']
X = data.drop('match_won_by', axis=1)

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
import pandas as pd
import numpy as np


data = pd.read_csv("train_IPL.csv")


matches = data.groupby('Match ID').agg(
    Date=('Date', 'first'),
    Bat_First=('Bat First', 'first'),
    Bat_Second=('Bat Second', 'first'),
    match_won_by=('match_won_by', 'first'),
    result_type=('result_type', 'first')
).reset_index()


matches = matches[matches['result_type'].isna()]


sample = pd.read_csv("sample_submission.csv")


submission = sample.copy()
submission['A_small'] = 0.28
submission['A_big'] = 0.22
submission['B_small'] = 0.28
submission['B_big'] = 0.22

submission.to_csv("submission.csv", index=False)
print("Submission created!")
print(submission.head())

C:\Users\sidak\AppData\Local\Temp\ipykernel_12284\3638075332.py:5: DtypeWarning: Columns (35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("train_IPL.csv")

Submission created!
  match_id  A_small  A_big  B_small  B_big
0  1473488     0.28   0.22     0.28   0.22
1  1473489     0.28   0.22     0.28   0.22
2  1473490     0.28   0.22     0.28   0.22
3  1473491     0.28   0.22     0.28   0.22
4  1473492     0.28   0.22     0.28   0.22

In [45]:
sample = pd.read_csv("sample_submission.csv")

submission = sample.copy()

submission["A_small"] = 0.28
submission["A_big"] = 0.22
submission["B_small"] = 0.28
submission["B_big"] = 0.22

print(submission.shape)

print(submission.head())

submission.to_csv("submission.csv", index=False)

print("Submission created!")

(53, 5)
  match_id  A_small  A_big  B_small  B_big
0  1473488     0.28   0.22     0.28   0.22
1  1473489     0.28   0.22     0.28   0.22
2  1473490     0.28   0.22     0.28   0.22
3  1473491     0.28   0.22     0.28   0.22
4  1473492     0.28   0.22     0.28   0.22
Submission created!

In [46]:
import pandas as pd
import numpy as np

sample = pd.read_csv("sample_submission.csv")
matches = pd.read_csv("public_lb_matches.csv")

submission = sample.copy()

np.random.seed(42)

A_small = []
A_big = []
B_small = []
B_big = []

for i in range(len(submission)):

    a_small = np.random.uniform(0.15, 0.40)
    a_big = np.random.uniform(0.10, 0.35)
    b_small = np.random.uniform(0.15, 0.40)
    b_big = np.random.uniform(0.10, 0.35)

    total = a_small + a_big + b_small + b_big

    A_small.append(a_small / total)
    A_big.append(a_big / total)
    B_small.append(b_small / total)
    B_big.append(b_big / total)

submission["A_small"] = A_small
submission["A_big"] = A_big
submission["B_small"] = B_small
submission["B_big"] = B_big

print(submission.head())

print(submission.shape)

submission.to_csv("submission_advanced.csv", index=False)

print("Advanced submission created!")

  match_id   A_small     A_big   B_small     B_big
0  1473488  0.209313  0.290108  0.286087  0.214493
1  1473489  0.233608  0.171801  0.203346  0.391245
2  1473490  0.279350  0.257710  0.144333  0.318607
3  1473491  0.420070  0.179571  0.229273  0.171086
4  1473492  0.254560  0.260335  0.290511  0.194593
(53, 5)
Advanced submission created!

In [48]:
import pandas as pd
import numpy as np

sample = pd.read_csv("sample_submission.csv")

submission = sample.copy()

np.random.seed(42)

submission["A_small"] = np.random.normal(0.25, 0.015, len(submission))
submission["A_big"] = np.random.normal(0.25, 0.015, len(submission))
submission["B_small"] = np.random.normal(0.25, 0.015, len(submission))
submission["B_big"] = np.random.normal(0.25, 0.015, len(submission))

submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]] = submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]].clip(0.18, 0.32)

row_sum = submission[
    ["A_small", "A_big", "B_small", "B_big"]
].sum(axis=1)

submission["A_small"] /= row_sum
submission["A_big"] /= row_sum
submission["B_small"] /= row_sum
submission["B_big"] /= row_sum

print(submission.head())

submission.to_csv("submission_smooth.csv", index=False)

print("Smooth submission created!")

  match_id   A_small     A_big   B_small     B_big
0  1473488  0.244083  0.245718  0.263843  0.246356
1  1473489  0.247582  0.265097  0.252268  0.235053
2  1473490  0.249881  0.253974  0.244251  0.251893
3  1473491  0.265797  0.231278  0.242454  0.260471
4  1473492  0.259254  0.258070  0.232676  0.250000
Smooth submission created!

In [50]:
import pandas as pd
import numpy as np

sample = pd.read_csv("sample_submission.csv")

submission = sample.copy()

np.random.seed(42)

A_small = np.random.normal(0.27, 0.02, len(submission))
A_big = np.random.normal(0.23, 0.02, len(submission))
B_small = np.random.normal(0.27, 0.02, len(submission))
B_big = np.random.normal(0.23, 0.02, len(submission))

submission["A_small"] = A_small
submission["A_big"] = A_big
submission["B_small"] = B_small
submission["B_big"] = B_big

submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]] = submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]].clip(0.10, 0.40)

row_sum = submission[
    ["A_small", "A_big", "B_small", "B_big"]
].sum(axis=1)

submission["A_small"] /= row_sum
submission["A_big"] /= row_sum
submission["B_small"] /= row_sum
submission["B_big"] /= row_sum

print(submission.head())

print(submission.shape)

submission.to_csv("submission_final.csv", index=False)

print("Final submission created!")

  match_id   A_small     A_big   B_small     B_big
0  1473488  0.260884  0.225749  0.286782  0.226585
1  1473489  0.266741  0.250157  0.272986  0.210117
2  1473490  0.268847  0.236230  0.261433  0.233490
3  1473491  0.290199  0.205934  0.259341  0.244526
4  1473492  0.283961  0.239543  0.247901  0.228595
(53, 5)
Final submission created!

In [51]:
import pandas as pd
import numpy as np

sample = pd.read_csv("sample_submission.csv")

submission = sample.copy()

np.random.seed(42)

A_small = np.random.beta(2.5, 3.5, len(submission))
A_big = np.random.beta(2.0, 4.0, len(submission))
B_small = np.random.beta(2.5, 3.5, len(submission))
B_big = np.random.beta(2.0, 4.0, len(submission))

submission["A_small"] = A_small
submission["A_big"] = A_big
submission["B_small"] = B_small
submission["B_big"] = B_big

row_sum = submission[
    ["A_small", "A_big", "B_small", "B_big"]
].sum(axis=1)

submission["A_small"] /= row_sum
submission["A_big"] /= row_sum
submission["B_small"] /= row_sum
submission["B_big"] /= row_sum

submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]] = submission[[
    "A_small",
    "A_big",
    "B_small",
    "B_big"
]].round(4)

print(submission.head())

print(submission.shape)

submission.to_csv("submission_110.csv", index=False)

print("Submission for ~1.10 attempt created!")

  match_id  A_small   A_big  B_small   B_big
0  1473488   0.4146  0.1554   0.2307  0.1993
1  1473489   0.2523  0.3389   0.2779  0.1309
2  1473490   0.4072  0.0908   0.3090  0.1930
3  1473491   0.2837  0.2239   0.2697  0.2227
4  1473492   0.5198  0.2765   0.0836  0.1202
(53, 5)
Submission for ~1.10 attempt created!